name: dart_example
description: A sample command-line application with basic argument parsing.
publish_to: none
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  wurm_atlas:
    path: ../../
  args: ^2.4.2
  image: ^4.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
